name: DevOps Scripts CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run sample script
      run: echo "🚀 Hello Mashu, your first CI pipeline is running!"
